# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - git clone https://gitlab.com/da_doomer/markdown-slides.git
    - cd markdown-slides
    - python make.py presentation.md --include media
    - mv presentation ../public
  artifacts:
    paths:
      - public
  only:
    - master
