image: python:3.8-alpine

pages:
  stage: deploy
  script:
    - python -m pip install git+https://gitlab.com/da_doomer/markdown-slides.git
    - mdslides example/presentation.md --include example/media
    - mv presentation public
  artifacts:
    paths:
      - public
  only:
    - master
