image: alpine

pages:
  stage: deploy
  script:
    - apk --no-cache add py3-pip python3-dev git
    - pip3 install git+https://gitlab.com/da_doomer/markdown-slides.git
    - mdslides example/presentation.md --include example/media
    - mv presentation public
  artifacts:
    paths:
      - public
  only:
    - master
